language: node_js
node_js:
  - node
script:
  - node --version && npm --version && yarn --version
  - yarn build:ci
after_success:
  - yarn codecov
  - yarn travis-deploy-once "yarn semantic-release"
os:
  - linux