language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - node
  - lts/*
script: yarn ci
jobs:
  include:
    - stage: semantic-release
      if: branch = master
      node_js: node
      script: 
        - yarn ci
        - yarn codecov
        - yarn release
